import type { Metadata } from "next";
import { BusinessLanding } from "@/components/seo/BusinessLanding";

export const metadata: Metadata = {
  title: "Logiciel de jardin — Plan à l'échelle sur photo, cultures et récoltes",
  description: "Dessinez le plan de votre jardin à l'échelle sur une photo aérienne, avec planches, arbres et plantes à leur vraie taille, puis suivez cultures, semis, arrosage et récoltes. Logiciel de jardin Gleba, gratuit et open source.",
  alternates: { canonical: "https://gleba.fr/logiciel-jardin" },
  openGraph: { title: "Logiciel de plan de jardin à l'échelle — Gleba", description: "Importez une photo aérienne, dessinez votre jardin à la bonne échelle avec plantes et arbres à leur taille, puis suivez cultures et récoltes.", url: "https://gleba.fr/logiciel-jardin", type: "article" },
};

export default function Page() {
  return <BusinessLanding breadcrumb="Logiciel de jardin" currentPath="/logiciel-jardin" eyebrow="Plan sur photo · À l'échelle · Cultures · Récoltes" title="Le logiciel de jardin" highlightedTitle="pour dessiner votre jardin à l'échelle" introduction="Gleba permet de dessiner votre jardin à la bonne échelle, directement sur une photo aérienne ou une capture satellite de votre terrain. Planches, arbres et plantes apparaissent à leur vraie taille, puis vous suivez au même endroit les cultures, semis, interventions et récoltes. Le plan reste le fil conducteur : chaque planche dessinée peut accueillir des cultures et conserver leur historique." proof="l'éditeur importe une photo de fond et la met à l'échelle par deux points de calibration ; les planches sont dessinées aux vraies dimensions, les plantes et les arbres à leur empreinte à maturité et à l'envergure adulte lorsque la donnée est disponible ; un outil de mesure et un export PNG sont disponibles ; les cultures, le calendrier de semis, les associations et les récoltes partagent ensuite le même jardin." screenshot={{ src: "/screenshots/gleba-plan-jardin.png", alt: "Plan 2D d'un jardin dans Gleba avec planches, arbres et plantes dessinés à l'échelle et légende des cultures", caption: "Plan du compte de démonstration : planches, arbres et cultures dessinés à leur vraie taille, avec surface cultivée et surface de canopée calculées." }} capabilities={[
    { title: "Plan sur photo aérienne", description: "Importez une capture Google Maps, une photo de drone ou un plan cadastral en fond, puis dessinez par-dessus. Le calque de fond guide le tracé de votre jardin réel." },
    { title: "Mise à l'échelle en 2 points", description: "Cliquez deux points sur le fond et saisissez la distance réelle : le plan se cale automatiquement à la bonne échelle en mètres." },
    { title: "Planches aux vraies dimensions", description: "Tracez chaque planche et positionnez arbres et objets à leurs coordonnées et surfaces réelles, avec zoom, plein écran et déplacement au doigt." },
    { title: "Plantes dessinées à leur taille", description: "Selon l'espacement, la densité et l'étalement à maturité de l'espèce, les cultures s'affichent en cercles à l'échelle le long des rangs — ou en rangs simples quand la donnée manque ou que la densité est trop forte." },
    { title: "Arbres à l'envergure adulte", description: "Quand son envergure adulte est renseignée ou disponible dans le référentiel, l'arbre affiche la projection de son houppier à taille adulte, pour anticiper l'ombre portée et l'espace occupé." },
    { title: "Outil de mesure", description: "Mesurez une distance directement sur le plan en deux clics, avec l'affichage en direct au centimètre près." },
    { title: "Export PNG du plan", description: "Exportez le plan complet, fond photo inclus, en image PNG pour l'imprimer, le partager ou l'archiver." },
    { title: "Cultures et calendrier de semis", description: "Suivez espèce, variété, planche, dates, état et récoltes, en vous appuyant sur les périodes de semis, plantation et récolte des espèces." },
    { title: "Associations et récoltes", description: "Vérifiez les associations favorables ou incompatibles avant de composer une planche, puis notez interventions et récoltes au fil des saisons." },
  ]} workflowTitle="De la photo de votre terrain au carnet du jardin" workflow={[
    { title: "Importer et caler", description: "Chargez une photo aérienne de votre terrain en fond, puis calez l'échelle en deux points pour dessiner aux vraies dimensions." },
    { title: "Dessiner et planter", description: "Tracez planches, arbres et objets, affectez des cultures aux planches : plantes et houppiers s'affichent à leur taille réelle." },
    { title: "Suivre et partager", description: "Notez interventions et récoltes au fil des saisons, mesurez, puis exportez le plan en PNG pour l'imprimer ou le partager." },
  ]} limits="Gleba est un outil pour dessiner et documenter les choix du jardinier : il ne conçoit pas le jardin à votre place et ne place pas automatiquement les plantes. Les tailles affichées proviennent du référentiel et sont des ordres de grandeur à adapter à votre variété, votre sol et votre taille ; aucun rendement ni date de réussite n'est garanti." faqs={[
    { question: "Puis-je dessiner mon jardin à partir d'une photo aérienne ?", answer: "Oui. Vous importez une capture Google Maps, une photo de drone ou un plan cadastral en image de fond, vous la mettez à l'échelle en cliquant deux points et en indiquant la distance réelle, puis vous dessinez planches, arbres et objets par-dessus, aux bonnes dimensions." },
    { question: "Les plantes et les arbres sont-ils à la bonne taille sur le plan ?", answer: "Oui, lorsque les données le permettent : les cultures s'affichent en cercles à l'échelle selon leur espacement et leur étalement à maturité (sinon en rangs simples), et les arbres avec la projection de leur houppier adulte quand l'envergure est renseignée. Ces tailles proviennent du référentiel et restent des ordres de grandeur à adapter." },
    { question: "Puis-je imprimer ou partager le plan de mon jardin ?", answer: "Oui. Un export PNG génère une image du plan complet, fond photo compris, que vous pouvez imprimer, partager ou archiver." },
    { question: "Gleba convient-il à un jardin familial ou à un potager amateur ?", answer: "Oui. Les mêmes modules servent au jardin familial, au potager amateur, au jardin pédagogique comme à la micro-ferme. Vous n'utilisez que les fonctions dont vous avez besoin." },
    { question: "Puis-je suivre à la fois légumes et arbres fruitiers ?", answer: "Oui. Le jardin peut contenir des planches de cultures et des arbres ; le module Verger complète le suivi des arbres fruitiers si besoin." },
    { question: "Le logiciel fonctionne-t-il sur smartphone ?", answer: "Oui. L'application web est responsive et l'éditeur gère le tactile : déplacement des éléments au doigt et zoom à deux doigts." },
    { question: "Gleba est-il gratuit et open source ?", answer: "Le code est publié sous licence AGPL-3.0 et le dépôt contient une configuration Docker pour l'auto-hébergement. Un compte de démonstration est accessible sans installation." },
  ]} />;
}
