-- Catalogue officiel complet des modes compagnie / équin / NAC.
-- Migration corrective additive : la première migration de filière ne
-- contenait que 9 espèces et aucune race. Cette migration est générée depuis
-- src/lib/elevage/catalogue-compagnie.ts et reste idempotente.
-- Espèces : 29. Associations race/variété : 410.

INSERT INTO "especes_animales"
  ("espece_animale", "nom", "type", "filiere", "production",
   "categorie_reglementaire", "productions", "duree_gestation",
   "duree_couvaison", "poids_adulte", "couleur", "description")
VALUES
  ('chien', 'Chien', 'mammifere_grand', 'compagnie', 'compagnie', 'Carnivore domestique', ARRAY[]::TEXT[], 63, NULL, 25, '#8b5e3c', 'Élevage canin. Identification I-CAD obligatoire avant 4 mois ; races au LOF (SCC).'),
  ('chat', 'Chat', 'mammifere_petit', 'compagnie', 'compagnie', 'Carnivore domestique', ARRAY[]::TEXT[], 65, NULL, 4, '#6b7280', 'Élevage félin. Identification I-CAD obligatoire avant 7 mois ; races au LOOF.'),
  ('cheval', 'Cheval', 'mammifere_grand', 'equin', 'compagnie', 'Équin', ARRAY[]::TEXT[], 340, NULL, 500, '#7c5a3a', 'Équidé : carte d''immatriculation SIRE, transpondeur et document d''identification obligatoires.'),
  ('poney', 'Poney', 'mammifere_grand', 'equin', 'compagnie', 'Équin', ARRAY[]::TEXT[], 335, NULL, 300, '#a1724a', 'Équidé de taille ≤ 1,48 m au garrot (toisage SIRE). Mêmes obligations d''identification que le cheval.'),
  ('ane', 'Âne', 'mammifere_grand', 'equin', 'compagnie', 'Équin', ARRAY[]::TEXT[], 365, NULL, 250, '#9ca3af', 'Équidé. Gestation longue (≈ 12 mois). Identification SIRE.'),
  ('mulet', 'Mulet / Bardot', 'mammifere_grand', 'equin', 'compagnie', 'Équin', ARRAY[]::TEXT[], 350, NULL, 400, '#8a8578', 'Hybride âne × cheval, stérile : pas de reproduction attendue. Immatriculation SIRE en tant qu''équidé.'),
  ('furet', 'Furet', 'mammifere_petit', 'nac', 'compagnie', 'Carnivore domestique', ARRAY[]::TEXT[], 42, NULL, 1.2, '#d6c39a', 'Mustélidé de compagnie : identification I-CAD et vaccination rage recommandées (obligatoires pour voyager).'),
  ('lapin_nain', 'Lapin nain', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 31, NULL, 1.5, '#c4b5a0', 'Lagomorphe de compagnie. Vaccination myxomatose/VHD conseillée en élevage.'),
  ('cobaye', 'Cochon d''Inde', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 68, NULL, 1, '#c98b5e', 'Rongeur de compagnie. Gestation longue, petits nidicoles autonomes.'),
  ('hamster', 'Hamster', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 18, NULL, 0.15, '#e0b06b', 'Rongeur de compagnie, solitaire (le doré surtout) : loger séparément après sevrage.'),
  ('rat', 'Rat domestique', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 22, NULL, 0.45, '#94a3b8', 'Rongeur social de compagnie (Rattus norvegicus domestica) : à maintenir en groupe de même sexe.'),
  ('souris', 'Souris domestique', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 20, NULL, 0.03, '#cbd5e1', 'Rongeur de compagnie. Maturité très précoce (5-6 semaines) : séparer les sexes tôt.'),
  ('gerbille', 'Gerbille', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 25, NULL, 0.08, '#d9a86c', 'Gerbille de Mongolie : rongeur diurne, vit en couple stable ou en fratrie.'),
  ('chinchilla', 'Chinchilla', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 111, NULL, 0.6, '#a8a29e', 'Rongeur de compagnie : gestation longue (≈ 111 j), petits nés déjà poilus et autonomes. Bain de sable indispensable.'),
  ('octodon', 'Octodon (dègue du Chili)', 'mammifere_petit', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], 90, NULL, 0.25, '#b08968', 'Rongeur diurne social. Prédisposition au diabète : aucun aliment sucré.'),
  ('cochon_nain', 'Cochon nain', 'mammifere_grand', 'nac', 'compagnie', 'Porcin', ARRAY[]::TEXT[], 114, NULL, 70, '#e8b4b8', 'Suidé : détention soumise à déclaration (EDE/BDPORC), interdiction de nourrir avec des déchets de cuisine. Poids adulte souvent très sous-estimé.'),
  ('perruche', 'Perruche', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 18, 0.04, '#4ade80', 'Oiseau d''ornement. Élevage en volière ; marquage par bague fermée pour la traçabilité des jeunes.'),
  ('calopsitte', 'Calopsitte élégante', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 19, 0.1, '#fbbf24', 'Perruche huppée d''Australie. Couples reproducteurs stables, 4-6 œufs par couvée.'),
  ('inseparable', 'Inséparable', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 23, 0.05, '#34d399', 'Agapornis : petit psittacidé vivant en couple. Bague fermée conseillée pour les jeunes.'),
  ('perroquet', 'Perroquet', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 28, 0.45, '#38bdf8', 'Psittacidé de grande taille : espèces majoritairement CITES (annexe I ou II) — marquage, registre d''élevage et certificats de cession obligatoires.'),
  ('canari', 'Canari', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 14, 0.02, '#facc15', 'Oiseau d''ornement (chant, posture, couleur). 2 à 3 couvées par saison.'),
  ('mandarin', 'Diamant mandarin', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 14, 0.013, '#fb923c', 'Estrildidé grégaire, reproduction facile en volière. Limiter les couvées à 3 par an.'),
  ('tortue_terrestre', 'Tortue terrestre', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 90, 3, '#84cc16', 'Espèces CITES : registre d''élevage (i-Fap/AFB), marquage et déclaration de détention obligatoires selon l''espèce et le nombre. Hibernation à respecter.'),
  ('gecko_leopard', 'Gecko léopard', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 50, 0.07, '#fcd34d', 'Eublepharis macularius : reptile terrestre nocturne, détermination du sexe par la température d''incubation.'),
  ('gecko_crete', 'Gecko à crête', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 65, 0.045, '#f97316', 'Correlophus ciliatus : arboricole, pontes de 2 œufs répétées sur la saison.'),
  ('pogona', 'Agame barbu (Pogona)', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 60, 0.45, '#f59e0b', 'Pogona vitticeps : lézard diurne héliophile (UVB indispensables). Pontes de 15-25 œufs.'),
  ('serpent_des_bles', 'Serpent des blés', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 60, 0.9, '#ef4444', 'Pantherophis guttatus : colubridé non venimeux, l''espèce d''initiation. Ponte après cycle hivernal.'),
  ('python_royal', 'Python royal', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 55, 1.8, '#78350f', 'Python regius : CITES annexe II (certificat de cession). Éviter les morphs à troubles neurologiques (type « spider ») en sélection.'),
  ('axolotl', 'Axolotl', 'autre', 'nac', 'compagnie', 'Autre', ARRAY[]::TEXT[], NULL, 15, 0.12, '#f9a8d4', 'Amphibien néotène aquatique (Ambystoma mexicanum), CITES annexe II. Eau fraîche 16-18 °C, jamais de gravier ingérable.')
ON CONFLICT ("espece_animale") DO UPDATE
SET "filiere" = EXCLUDED."filiere";

INSERT INTO "races_animales"
  ("id", "nom", "espece_animale_id", "origine", "aptitudes", "description")
VALUES
  ('cat_' || substr(md5('chien::Berger allemand'), 1, 20), 'Berger allemand', 'chien', 'Allemagne', ARRAY['garde', 'utilitaire', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Berger belge Malinois'), 1, 20), 'Berger belge Malinois', 'chien', 'Belgique', ARRAY['garde', 'utilitaire', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Berger belge Tervueren'), 1, 20), 'Berger belge Tervueren', 'chien', 'Belgique', ARRAY['garde', 'sport', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Berger belge Groenendael'), 1, 20), 'Berger belge Groenendael', 'chien', 'Belgique', ARRAY['garde', 'sport', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Berger australien'), 1, 20), 'Berger australien', 'chien', 'États-Unis', ARRAY['troupeau', 'sport', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Border collie'), 1, 20), 'Border collie', 'chien', 'Royaume-Uni', ARRAY['troupeau', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Beauceron'), 1, 20), 'Beauceron', 'chien', 'France', ARRAY['garde', 'troupeau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Briard'), 1, 20), 'Briard', 'chien', 'France', ARRAY['troupeau', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Berger des Pyrénées'), 1, 20), 'Berger des Pyrénées', 'chien', 'France', ARRAY['troupeau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Montagne des Pyrénées'), 1, 20), 'Montagne des Pyrénées', 'chien', 'France', ARRAY['garde troupeau']::TEXT[], 'Patou : chien de protection de troupeau.'),
  ('cat_' || substr(md5('chien::Berger blanc suisse'), 1, 20), 'Berger blanc suisse', 'chien', 'Suisse', ARRAY['compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Colley à poil long'), 1, 20), 'Colley à poil long', 'chien', 'Royaume-Uni', ARRAY['compagnie', 'troupeau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Shetland (Sheltie)'), 1, 20), 'Shetland (Sheltie)', 'chien', 'Royaume-Uni', ARRAY['troupeau', 'compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Welsh corgi Pembroke'), 1, 20), 'Welsh corgi Pembroke', 'chien', 'Royaume-Uni', ARRAY['troupeau', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bouvier bernois'), 1, 20), 'Bouvier bernois', 'chien', 'Suisse', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bouvier des Flandres'), 1, 20), 'Bouvier des Flandres', 'chien', 'Belgique', ARRAY['garde', 'troupeau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Chien-loup tchécoslovaque'), 1, 20), 'Chien-loup tchécoslovaque', 'chien', 'Tchéquie', ARRAY['sport', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Rottweiler'), 1, 20), 'Rottweiler', 'chien', 'Allemagne', ARRAY['garde', 'utilitaire']::TEXT[], 'Chien de 2e catégorie (loi du 6 janvier 1999) : permis de détention, muselière et laisse sur la voie publique.'),
  ('cat_' || substr(md5('chien::Doberman'), 1, 20), 'Doberman', 'chien', 'Allemagne', ARRAY['garde', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Boxer'), 1, 20), 'Boxer', 'chien', 'Allemagne', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Schnauzer moyen'), 1, 20), 'Schnauzer moyen', 'chien', 'Allemagne', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Dogue allemand'), 1, 20), 'Dogue allemand', 'chien', 'Allemagne', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Dogue de Bordeaux'), 1, 20), 'Dogue de Bordeaux', 'chien', 'France', ARRAY['garde', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Cane corso'), 1, 20), 'Cane corso', 'chien', 'Italie', ARRAY['garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Mastiff'), 1, 20), 'Mastiff', 'chien', 'Royaume-Uni', ARRAY['garde']::TEXT[], 'Non inscrit au LOF, relève de la 1re catégorie (élevage interdit).'),
  ('cat_' || substr(md5('chien::Bullmastiff'), 1, 20), 'Bullmastiff', 'chien', 'Royaume-Uni', ARRAY['garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Tosa'), 1, 20), 'Tosa', 'chien', 'Japon', ARRAY['garde']::TEXT[], '2e catégorie si inscrit au LOF, 1re catégorie sinon (élevage interdit).'),
  ('cat_' || substr(md5('chien::Terre-Neuve'), 1, 20), 'Terre-Neuve', 'chien', 'Canada', ARRAY['eau', 'compagnie', 'secours']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Saint-Bernard'), 1, 20), 'Saint-Bernard', 'chien', 'Suisse', ARRAY['compagnie', 'secours']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Léonberg'), 1, 20), 'Léonberg', 'chien', 'Allemagne', ARRAY['compagnie', 'eau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bouledogue français'), 1, 20), 'Bouledogue français', 'chien', 'France', ARRAY['compagnie']::TEXT[], 'Race brachycéphale : surveiller la tolérance à l''effort et à la chaleur.'),
  ('cat_' || substr(md5('chien::Bulldog anglais'), 1, 20), 'Bulldog anglais', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], 'Race brachycéphale ; mise-bas souvent par césarienne.'),
  ('cat_' || substr(md5('chien::Shar peï'), 1, 20), 'Shar peï', 'chien', 'Chine', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::American Staffordshire terrier'), 1, 20), 'American Staffordshire terrier', 'chien', 'États-Unis', ARRAY['compagnie', 'sport']::TEXT[], '2e catégorie si inscrit au LOF, 1re catégorie sinon (élevage interdit).'),
  ('cat_' || substr(md5('chien::Staffordshire bull terrier'), 1, 20), 'Staffordshire bull terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bull terrier'), 1, 20), 'Bull terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Jack Russell terrier'), 1, 20), 'Jack Russell terrier', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Parson Russell terrier'), 1, 20), 'Parson Russell terrier', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Fox terrier à poil dur'), 1, 20), 'Fox terrier à poil dur', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Yorkshire terrier'), 1, 20), 'Yorkshire terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::West Highland white terrier'), 1, 20), 'West Highland white terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Cairn terrier'), 1, 20), 'Cairn terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie', 'chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Scottish terrier'), 1, 20), 'Scottish terrier', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Airedale terrier'), 1, 20), 'Airedale terrier', 'chien', 'Royaume-Uni', ARRAY['utilitaire', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Teckel poil ras'), 1, 20), 'Teckel poil ras', 'chien', 'Allemagne', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Teckel poil long'), 1, 20), 'Teckel poil long', 'chien', 'Allemagne', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Teckel poil dur'), 1, 20), 'Teckel poil dur', 'chien', 'Allemagne', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Beagle'), 1, 20), 'Beagle', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Basset hound'), 1, 20), 'Basset hound', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Basset artésien normand'), 1, 20), 'Basset artésien normand', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Grand bleu de Gascogne'), 1, 20), 'Grand bleu de Gascogne', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Griffon nivernais'), 1, 20), 'Griffon nivernais', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Rhodesian ridgeback'), 1, 20), 'Rhodesian ridgeback', 'chien', 'Afrique du Sud', ARRAY['chasse', 'garde', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Épagneul breton'), 1, 20), 'Épagneul breton', 'chien', 'France', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Épagneul français'), 1, 20), 'Épagneul français', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Braque français type Pyrénées'), 1, 20), 'Braque français type Pyrénées', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Braque allemand à poil court'), 1, 20), 'Braque allemand à poil court', 'chien', 'Allemagne', ARRAY['chasse', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Braque hongrois (Vizsla)'), 1, 20), 'Braque hongrois (Vizsla)', 'chien', 'Hongrie', ARRAY['chasse', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Griffon Korthals'), 1, 20), 'Griffon Korthals', 'chien', 'France', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Weimaraner'), 1, 20), 'Weimaraner', 'chien', 'Allemagne', ARRAY['chasse', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Setter anglais'), 1, 20), 'Setter anglais', 'chien', 'Royaume-Uni', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Setter irlandais rouge'), 1, 20), 'Setter irlandais rouge', 'chien', 'Irlande', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Pointer'), 1, 20), 'Pointer', 'chien', 'Royaume-Uni', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Labrador retriever'), 1, 20), 'Labrador retriever', 'chien', 'Royaume-Uni', ARRAY['compagnie', 'chasse', 'assistance']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Golden retriever'), 1, 20), 'Golden retriever', 'chien', 'Royaume-Uni', ARRAY['compagnie', 'assistance', 'chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Retriever de la Nouvelle-Écosse'), 1, 20), 'Retriever de la Nouvelle-Écosse', 'chien', 'Canada', ARRAY['chasse', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Cocker anglais'), 1, 20), 'Cocker anglais', 'chien', 'Royaume-Uni', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Cocker américain'), 1, 20), 'Cocker américain', 'chien', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Springer anglais'), 1, 20), 'Springer anglais', 'chien', 'Royaume-Uni', ARRAY['chasse']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Barbet'), 1, 20), 'Barbet', 'chien', 'France', ARRAY['eau', 'chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Caniche'), 1, 20), 'Caniche', 'chien', 'France', ARRAY['compagnie', 'sport']::TEXT[], 'Quatre tailles : toy, nain, moyen, grand.'),
  ('cat_' || substr(md5('chien::Cavalier King Charles spaniel'), 1, 20), 'Cavalier King Charles spaniel', 'chien', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Chihuahua'), 1, 20), 'Chihuahua', 'chien', 'Mexique', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bichon frisé'), 1, 20), 'Bichon frisé', 'chien', 'France', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Bichon maltais'), 1, 20), 'Bichon maltais', 'chien', 'Italie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Coton de Tuléar'), 1, 20), 'Coton de Tuléar', 'chien', 'Madagascar', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Carlin'), 1, 20), 'Carlin', 'chien', 'Chine', ARRAY['compagnie']::TEXT[], 'Race brachycéphale : surveiller respiration et chaleur.'),
  ('cat_' || substr(md5('chien::Shih tzu'), 1, 20), 'Shih tzu', 'chien', 'Chine', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Lhassa apso'), 1, 20), 'Lhassa apso', 'chien', 'Tibet', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Spitz nain (poméranien)'), 1, 20), 'Spitz nain (poméranien)', 'chien', 'Allemagne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Épagneul nain continental (papillon)'), 1, 20), 'Épagneul nain continental (papillon)', 'chien', 'France', ARRAY['compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Boston terrier'), 1, 20), 'Boston terrier', 'chien', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Dalmatien'), 1, 20), 'Dalmatien', 'chien', 'Croatie', ARRAY['compagnie', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Husky sibérien'), 1, 20), 'Husky sibérien', 'chien', 'États-Unis', ARRAY['traîneau', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Malamute d''Alaska'), 1, 20), 'Malamute d''Alaska', 'chien', 'États-Unis', ARRAY['traîneau']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Samoyède'), 1, 20), 'Samoyède', 'chien', 'Russie', ARRAY['traîneau', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Akita inu'), 1, 20), 'Akita inu', 'chien', 'Japon', ARRAY['compagnie', 'garde']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Shiba inu'), 1, 20), 'Shiba inu', 'chien', 'Japon', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Basenji'), 1, 20), 'Basenji', 'chien', 'Afrique centrale', ARRAY['chasse', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Whippet'), 1, 20), 'Whippet', 'chien', 'Royaume-Uni', ARRAY['course', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Greyhound'), 1, 20), 'Greyhound', 'chien', 'Royaume-Uni', ARRAY['course']::TEXT[], NULL),
  ('cat_' || substr(md5('chien::Barzoï'), 1, 20), 'Barzoï', 'chien', 'Russie', ARRAY['course', 'compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Européen (celtic shorthair)'), 1, 20), 'Européen (celtic shorthair)', 'chat', 'Europe', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Maine coon'), 1, 20), 'Maine coon', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], 'Poil long. Dépister HCM et dysplasie de la hanche.'),
  ('cat_' || substr(md5('chat::Sacré de Birmanie'), 1, 20), 'Sacré de Birmanie', 'chat', 'France', ARRAY['compagnie']::TEXT[], 'Poil long, colourpoint aux gants blancs.'),
  ('cat_' || substr(md5('chat::Ragdoll'), 1, 20), 'Ragdoll', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], 'Poil long. Dépistage HCM conseillé.'),
  ('cat_' || substr(md5('chat::Ragamuffin'), 1, 20), 'Ragamuffin', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Bengal'), 1, 20), 'Bengal', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], 'Issu d''hybridation ancienne : générations F1-F4 réglementées, F5+ domestiques.'),
  ('cat_' || substr(md5('chat::Savannah'), 1, 20), 'Savannah', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], 'Hybride de serval : F1-F4 relèvent de la faune non domestique (autorisation de détention).'),
  ('cat_' || substr(md5('chat::Chausie'), 1, 20), 'Chausie', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::British shorthair'), 1, 20), 'British shorthair', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::British longhair'), 1, 20), 'British longhair', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Chartreux'), 1, 20), 'Chartreux', 'chat', 'France', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Persan'), 1, 20), 'Persan', 'chat', 'Iran', ARRAY['compagnie']::TEXT[], 'Brachycéphale à poil long : dépistage PKD, entretien quotidien.'),
  ('cat_' || substr(md5('chat::Exotic shorthair'), 1, 20), 'Exotic shorthair', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Sphynx'), 1, 20), 'Sphynx', 'chat', 'Canada', ARRAY['compagnie']::TEXT[], 'Sans poil : besoins thermiques et nettoyage cutané spécifiques.'),
  ('cat_' || substr(md5('chat::Peterbald'), 1, 20), 'Peterbald', 'chat', 'Russie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Donskoy'), 1, 20), 'Donskoy', 'chat', 'Russie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Siamois'), 1, 20), 'Siamois', 'chat', 'Thaïlande', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Thaï'), 1, 20), 'Thaï', 'chat', 'Thaïlande', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Oriental'), 1, 20), 'Oriental', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Balinais'), 1, 20), 'Balinais', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Tonkinois'), 1, 20), 'Tonkinois', 'chat', 'Canada', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Burmese'), 1, 20), 'Burmese', 'chat', 'Birmanie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Bombay'), 1, 20), 'Bombay', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Abyssin'), 1, 20), 'Abyssin', 'chat', 'Éthiopie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Somali'), 1, 20), 'Somali', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Norvégien'), 1, 20), 'Norvégien', 'chat', 'Norvège', ARRAY['compagnie']::TEXT[], 'Poil long, très rustique.'),
  ('cat_' || substr(md5('chat::Sibérien'), 1, 20), 'Sibérien', 'chat', 'Russie', ARRAY['compagnie']::TEXT[], 'Poil long, rustique.'),
  ('cat_' || substr(md5('chat::Neva Masquerade'), 1, 20), 'Neva Masquerade', 'chat', 'Russie', ARRAY['compagnie']::TEXT[], 'Variété colourpoint du sibérien.'),
  ('cat_' || substr(md5('chat::Angora turc'), 1, 20), 'Angora turc', 'chat', 'Turquie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Turc de Van'), 1, 20), 'Turc de Van', 'chat', 'Turquie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Bleu russe'), 1, 20), 'Bleu russe', 'chat', 'Russie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Nebelung'), 1, 20), 'Nebelung', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Korat'), 1, 20), 'Korat', 'chat', 'Thaïlande', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Mau égyptien'), 1, 20), 'Mau égyptien', 'chat', 'Égypte', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Ocicat'), 1, 20), 'Ocicat', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Devon rex'), 1, 20), 'Devon rex', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Cornish rex'), 1, 20), 'Cornish rex', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::German rex'), 1, 20), 'German rex', 'chat', 'Allemagne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Selkirk rex'), 1, 20), 'Selkirk rex', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::LaPerm'), 1, 20), 'LaPerm', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Scottish fold'), 1, 20), 'Scottish fold', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], 'Oreilles pliées liées à une ostéochondrodysplasie : mariage fold × straight imposé.'),
  ('cat_' || substr(md5('chat::Scottish straight'), 1, 20), 'Scottish straight', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Highland fold'), 1, 20), 'Highland fold', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Highland straight'), 1, 20), 'Highland straight', 'chat', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::American curl'), 1, 20), 'American curl', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::American shorthair'), 1, 20), 'American shorthair', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Manx'), 1, 20), 'Manx', 'chat', 'Île de Man', ARRAY['compagnie']::TEXT[], 'Anomalie caudale : ne jamais accoupler deux sujets sans queue.'),
  ('cat_' || substr(md5('chat::Snowshoe'), 1, 20), 'Snowshoe', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Singapura'), 1, 20), 'Singapura', 'chat', 'Singapour', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Pixie-bob'), 1, 20), 'Pixie-bob', 'chat', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Sokoké'), 1, 20), 'Sokoké', 'chat', 'Kenya', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('chat::Khao Manee'), 1, 20), 'Khao Manee', 'chat', 'Thaïlande', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Selle français'), 1, 20), 'Selle français', 'cheval', 'France', ARRAY['selle', 'sport', 'obstacle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Anglo-arabe'), 1, 20), 'Anglo-arabe', 'cheval', 'France', ARRAY['selle', 'sport', 'endurance']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Pur-sang arabe'), 1, 20), 'Pur-sang arabe', 'cheval', 'Péninsule arabique', ARRAY['endurance', 'selle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Pur-sang anglais'), 1, 20), 'Pur-sang anglais', 'cheval', 'Royaume-Uni', ARRAY['course', 'selle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::AQPS'), 1, 20), 'AQPS', 'cheval', 'France', ARRAY['course', 'selle']::TEXT[], 'Autre que pur-sang : cheval de course d''obstacle.'),
  ('cat_' || substr(md5('cheval::Trotteur français'), 1, 20), 'Trotteur français', 'cheval', 'France', ARRAY['course', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Hanovrien'), 1, 20), 'Hanovrien', 'cheval', 'Allemagne', ARRAY['sport', 'dressage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Holsteiner'), 1, 20), 'Holsteiner', 'cheval', 'Allemagne', ARRAY['sport', 'obstacle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Oldenbourg'), 1, 20), 'Oldenbourg', 'cheval', 'Allemagne', ARRAY['sport', 'dressage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Westphalien'), 1, 20), 'Westphalien', 'cheval', 'Allemagne', ARRAY['sport', 'dressage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Trakehner'), 1, 20), 'Trakehner', 'cheval', 'Allemagne', ARRAY['sport', 'dressage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::KWPN'), 1, 20), 'KWPN', 'cheval', 'Pays-Bas', ARRAY['sport', 'obstacle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Lusitanien'), 1, 20), 'Lusitanien', 'cheval', 'Portugal', ARRAY['dressage', 'travail', 'selle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Pure race espagnole (PRE)'), 1, 20), 'Pure race espagnole (PRE)', 'cheval', 'Espagne', ARRAY['dressage', 'selle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Frison'), 1, 20), 'Frison', 'cheval', 'Pays-Bas', ARRAY['attelage', 'dressage', 'spectacle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Akhal-Téké'), 1, 20), 'Akhal-Téké', 'cheval', 'Turkménistan', ARRAY['endurance', 'selle']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Barbe'), 1, 20), 'Barbe', 'cheval', 'Maghreb', ARRAY['selle', 'endurance']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Arabe-barbe'), 1, 20), 'Arabe-barbe', 'cheval', 'Maghreb', ARRAY['selle', 'endurance']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Quarter horse'), 1, 20), 'Quarter horse', 'cheval', 'États-Unis', ARRAY['western', 'loisir']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Paint horse'), 1, 20), 'Paint horse', 'cheval', 'États-Unis', ARRAY['western', 'loisir']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Appaloosa'), 1, 20), 'Appaloosa', 'cheval', 'États-Unis', ARRAY['western', 'loisir']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Criollo'), 1, 20), 'Criollo', 'cheval', 'Argentine', ARRAY['western', 'endurance']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Irish cob'), 1, 20), 'Irish cob', 'cheval', 'Irlande', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Curly'), 1, 20), 'Curly', 'cheval', 'États-Unis', ARRAY['loisir']::TEXT[], 'Poil bouclé, souvent mieux toléré par les personnes allergiques.'),
  ('cat_' || substr(md5('cheval::Camargue'), 1, 20), 'Camargue', 'cheval', 'France', ARRAY['travail', 'loisir']::TEXT[], 'Race rustique élevée en manade.'),
  ('cat_' || substr(md5('cheval::Mérens'), 1, 20), 'Mérens', 'cheval', 'France', ARRAY['loisir', 'randonnée']::TEXT[], 'Cheval de montagne ariégeois, très rustique.'),
  ('cat_' || substr(md5('cheval::Castillonnais'), 1, 20), 'Castillonnais', 'cheval', 'France', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Henson'), 1, 20), 'Henson', 'cheval', 'France', ARRAY['loisir', 'randonnée']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Comtois'), 1, 20), 'Comtois', 'cheval', 'France', ARRAY['trait', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Percheron'), 1, 20), 'Percheron', 'cheval', 'France', ARRAY['trait', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Breton'), 1, 20), 'Breton', 'cheval', 'France', ARRAY['trait', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Ardennais'), 1, 20), 'Ardennais', 'cheval', 'France', ARRAY['trait']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Trait du Nord'), 1, 20), 'Trait du Nord', 'cheval', 'France', ARRAY['trait']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Boulonnais'), 1, 20), 'Boulonnais', 'cheval', 'France', ARRAY['trait']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Auxois'), 1, 20), 'Auxois', 'cheval', 'France', ARRAY['trait']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Cob normand'), 1, 20), 'Cob normand', 'cheval', 'France', ARRAY['attelage', 'loisir']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Trait poitevin mulassier'), 1, 20), 'Trait poitevin mulassier', 'cheval', 'France', ARRAY['trait', 'mulassier']::TEXT[], 'Race support de la production mulassière avec le baudet du Poitou.'),
  ('cat_' || substr(md5('cheval::Haflinger'), 1, 20), 'Haflinger', 'cheval', 'Autriche', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Fjord'), 1, 20), 'Fjord', 'cheval', 'Norvège', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('cheval::Islandais'), 1, 20), 'Islandais', 'cheval', 'Islande', ARRAY['loisir', 'randonnée']::TEXT[], 'Allures supplémentaires (tölt).'),
  ('cat_' || substr(md5('poney::Poney français de selle'), 1, 20), 'Poney français de selle', 'poney', 'France', ARRAY['poney-club', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Connemara'), 1, 20), 'Connemara', 'poney', 'Irlande', ARRAY['sport', 'poney-club']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::New forest'), 1, 20), 'New forest', 'poney', 'Royaume-Uni', ARRAY['poney-club', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Welsh mountain (section A)'), 1, 20), 'Welsh mountain (section A)', 'poney', 'Royaume-Uni', ARRAY['poney-club']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Welsh poney (section B)'), 1, 20), 'Welsh poney (section B)', 'poney', 'Royaume-Uni', ARRAY['poney-club', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Welsh poney de type cob (section C)'), 1, 20), 'Welsh poney de type cob (section C)', 'poney', 'Royaume-Uni', ARRAY['attelage', 'loisir']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Welsh cob (section D)'), 1, 20), 'Welsh cob (section D)', 'poney', 'Royaume-Uni', ARRAY['attelage', 'sport']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Shetland'), 1, 20), 'Shetland', 'poney', 'Royaume-Uni', ARRAY['poney-club', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Dartmoor'), 1, 20), 'Dartmoor', 'poney', 'Royaume-Uni', ARRAY['poney-club']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Exmoor'), 1, 20), 'Exmoor', 'poney', 'Royaume-Uni', ARRAY['loisir']::TEXT[], 'Poney primitif très rustique.'),
  ('cat_' || substr(md5('poney::Highland'), 1, 20), 'Highland', 'poney', 'Royaume-Uni', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Fell'), 1, 20), 'Fell', 'poney', 'Royaume-Uni', ARRAY['loisir', 'attelage']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Landais'), 1, 20), 'Landais', 'poney', 'France', ARRAY['loisir']::TEXT[], 'Race française à petits effectifs.'),
  ('cat_' || substr(md5('poney::Pottok'), 1, 20), 'Pottok', 'poney', 'France', ARRAY['loisir', 'randonnée']::TEXT[], 'Poney basque rustique.'),
  ('cat_' || substr(md5('poney::Poney des Amériques'), 1, 20), 'Poney des Amériques', 'poney', 'États-Unis', ARRAY['western', 'poney-club']::TEXT[], NULL),
  ('cat_' || substr(md5('poney::Poney de selle allemand'), 1, 20), 'Poney de selle allemand', 'poney', 'Allemagne', ARRAY['sport', 'poney-club']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Baudet du Poitou'), 1, 20), 'Baudet du Poitou', 'ane', 'France', ARRAY['mulassier', 'trait']::TEXT[], 'Race à très petits effectifs, support de la production mulassière.'),
  ('cat_' || substr(md5('ane::Âne normand'), 1, 20), 'Âne normand', 'ane', 'France', ARRAY['attelage', 'bât']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Âne du Cotentin'), 1, 20), 'Âne du Cotentin', 'ane', 'France', ARRAY['attelage', 'bât']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Âne de Provence'), 1, 20), 'Âne de Provence', 'ane', 'France', ARRAY['bât', 'randonnée']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Âne des Pyrénées'), 1, 20), 'Âne des Pyrénées', 'ane', 'France', ARRAY['bât', 'randonnée']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Âne du Bourbonnais'), 1, 20), 'Âne du Bourbonnais', 'ane', 'France', ARRAY['attelage', 'bât']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Grand noir du Berry'), 1, 20), 'Grand noir du Berry', 'ane', 'France', ARRAY['attelage', 'trait']::TEXT[], NULL),
  ('cat_' || substr(md5('ane::Âne commun'), 1, 20), 'Âne commun', 'ane', NULL, ARRAY['compagnie', 'débroussaillage']::TEXT[], 'Sans race définie : immatriculation SIRE en « origine constatée ».'),
  ('cat_' || substr(md5('ane::Âne miniature méditerranéen'), 1, 20), 'Âne miniature méditerranéen', 'ane', 'Italie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('mulet::Mulet poitevin'), 1, 20), 'Mulet poitevin', 'mulet', 'France', ARRAY['trait', 'bât']::TEXT[], NULL),
  ('cat_' || substr(md5('mulet::Mule des Pyrénées'), 1, 20), 'Mule des Pyrénées', 'mulet', 'France', ARRAY['bât', 'randonnée']::TEXT[], NULL),
  ('cat_' || substr(md5('mulet::Bardot'), 1, 20), 'Bardot', 'mulet', 'France', ARRAY['bât']::TEXT[], 'Produit inverse : père cheval × mère ânesse.'),
  ('cat_' || substr(md5('furet::Putoisé'), 1, 20), 'Putoisé', 'furet', NULL, ARRAY['variété']::TEXT[], 'Robe sauvage (masque et extrémités foncées).'),
  ('cat_' || substr(md5('furet::Zibeline'), 1, 20), 'Zibeline', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Champagne'), 1, 20), 'Champagne', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Chocolat'), 1, 20), 'Chocolat', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Cinnamon'), 1, 20), 'Cinnamon', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Albinos'), 1, 20), 'Albinos', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Blanc aux yeux noirs (DEW)'), 1, 20), 'Blanc aux yeux noirs (DEW)', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Argenté'), 1, 20), 'Argenté', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Panda'), 1, 20), 'Panda', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Blaze'), 1, 20), 'Blaze', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('furet::Silver mitt'), 1, 20), 'Silver mitt', 'furet', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Nain de couleur'), 1, 20), 'Nain de couleur', 'lapin_nain', 'Allemagne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Hermine de Lutterbach'), 1, 20), 'Hermine de Lutterbach', 'lapin_nain', 'France', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Nain bélier'), 1, 20), 'Nain bélier', 'lapin_nain', 'Pays-Bas', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Bélier anglais'), 1, 20), 'Bélier anglais', 'lapin_nain', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Rex nain'), 1, 20), 'Rex nain', 'lapin_nain', 'France', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Angora nain'), 1, 20), 'Angora nain', 'lapin_nain', 'Turquie', ARRAY['compagnie', 'poil']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Tête de lion'), 1, 20), 'Tête de lion', 'lapin_nain', 'Belgique', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Hollandais nain'), 1, 20), 'Hollandais nain', 'lapin_nain', 'Pays-Bas', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Papillon nain'), 1, 20), 'Papillon nain', 'lapin_nain', 'Allemagne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Polonais'), 1, 20), 'Polonais', 'lapin_nain', 'Pologne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Fuzzy lop'), 1, 20), 'Fuzzy lop', 'lapin_nain', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('lapin_nain::Nain satin'), 1, 20), 'Nain satin', 'lapin_nain', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Poil lisse (self)'), 1, 20), 'Poil lisse (self)', 'cobaye', 'Pérou', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Abyssin'), 1, 20), 'Abyssin', 'cobaye', 'Pérou', ARRAY['compagnie']::TEXT[], 'Poil en rosettes.'),
  ('cat_' || substr(md5('cobaye::Péruvien'), 1, 20), 'Péruvien', 'cobaye', 'Pérou', ARRAY['compagnie']::TEXT[], 'Poil long : toilettage indispensable.'),
  ('cat_' || substr(md5('cobaye::Sheltie'), 1, 20), 'Sheltie', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Coronet'), 1, 20), 'Coronet', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Texel'), 1, 20), 'Texel', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Rex'), 1, 20), 'Rex', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Alpaga'), 1, 20), 'Alpaga', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Mérino'), 1, 20), 'Mérino', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Skinny'), 1, 20), 'Skinny', 'cobaye', 'Pays-Bas', ARRAY['compagnie']::TEXT[], 'Quasi nu : besoins thermiques et alimentaires accrus.'),
  ('cat_' || substr(md5('cobaye::Baldwin'), 1, 20), 'Baldwin', 'cobaye', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cobaye::Himalayen'), 1, 20), 'Himalayen', 'cobaye', 'Royaume-Uni', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('hamster::Doré (syrien)'), 1, 20), 'Doré (syrien)', 'hamster', 'Syrie', ARRAY['compagnie']::TEXT[], 'Strictement solitaire à partir de 5 semaines.'),
  ('cat_' || substr(md5('hamster::Angora (syrien poil long)'), 1, 20), 'Angora (syrien poil long)', 'hamster', 'Syrie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('hamster::Nain russe (Campbell)'), 1, 20), 'Nain russe (Campbell)', 'hamster', 'Asie centrale', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('hamster::Nain Winter White'), 1, 20), 'Nain Winter White', 'hamster', 'Sibérie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('hamster::Roborovski'), 1, 20), 'Roborovski', 'hamster', 'Mongolie', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('hamster::Chinois'), 1, 20), 'Chinois', 'hamster', 'Chine', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Standard'), 1, 20), 'Standard', 'rat', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Rex'), 1, 20), 'Rex', 'rat', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Dumbo'), 1, 20), 'Dumbo', 'rat', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Husky'), 1, 20), 'Husky', 'rat', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Satin'), 1, 20), 'Satin', 'rat', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('rat::Nu (sphynx)'), 1, 20), 'Nu (sphynx)', 'rat', NULL, ARRAY['variété']::TEXT[], 'Sans poil : sensible au froid et aux lésions cutanées.'),
  ('cat_' || substr(md5('rat::Manx'), 1, 20), 'Manx', 'rat', NULL, ARRAY['variété']::TEXT[], 'Sans queue : thermorégulation et équilibre altérés.'),
  ('cat_' || substr(md5('souris::Standard'), 1, 20), 'Standard', 'souris', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('souris::Satin'), 1, 20), 'Satin', 'souris', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('souris::Angora'), 1, 20), 'Angora', 'souris', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('souris::Rex'), 1, 20), 'Rex', 'souris', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('souris::Nue'), 1, 20), 'Nue', 'souris', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Agouti (sauvage)'), 1, 20), 'Agouti (sauvage)', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Or'), 1, 20), 'Or', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Argentée'), 1, 20), 'Argentée', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Noire'), 1, 20), 'Noire', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Lilas'), 1, 20), 'Lilas', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Panda'), 1, 20), 'Panda', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gerbille::Pie'), 1, 20), 'Pie', 'gerbille', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Standard gris'), 1, 20), 'Standard gris', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Beige'), 1, 20), 'Beige', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Blanc mosaïque'), 1, 20), 'Blanc mosaïque', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Black velvet'), 1, 20), 'Black velvet', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Violet'), 1, 20), 'Violet', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Saphir'), 1, 20), 'Saphir', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('chinchilla::Ébène'), 1, 20), 'Ébène', 'chinchilla', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('octodon::Agouti (sauvage)'), 1, 20), 'Agouti (sauvage)', 'octodon', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('octodon::Bleu'), 1, 20), 'Bleu', 'octodon', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('octodon::Sable'), 1, 20), 'Sable', 'octodon', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('octodon::Pie'), 1, 20), 'Pie', 'octodon', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('cochon_nain::Kunekune'), 1, 20), 'Kunekune', 'cochon_nain', 'Nouvelle-Zélande', ARRAY['compagnie', 'pâturage']::TEXT[], NULL),
  ('cat_' || substr(md5('cochon_nain::Vietnamien (pot-bellied)'), 1, 20), 'Vietnamien (pot-bellied)', 'cochon_nain', 'Vietnam', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cochon_nain::Göttingen'), 1, 20), 'Göttingen', 'cochon_nain', 'Allemagne', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cochon_nain::Juliana'), 1, 20), 'Juliana', 'cochon_nain', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('cochon_nain::Mini-pig américain'), 1, 20), 'Mini-pig américain', 'cochon_nain', 'États-Unis', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Ondulée'), 1, 20), 'Ondulée', 'perruche', 'Australie', ARRAY['compagnie', 'volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Ondulée anglaise (de posture)'), 1, 20), 'Ondulée anglaise (de posture)', 'perruche', 'Royaume-Uni', ARRAY['exposition']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Catherine'), 1, 20), 'Catherine', 'perruche', 'Asie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::De Bourke'), 1, 20), 'De Bourke', 'perruche', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Omnicolore'), 1, 20), 'Omnicolore', 'perruche', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Turquoisine'), 1, 20), 'Turquoisine', 'perruche', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::Splendide'), 1, 20), 'Splendide', 'perruche', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::À croupion rouge'), 1, 20), 'À croupion rouge', 'perruche', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perruche::À collier'), 1, 20), 'À collier', 'perruche', 'Asie', ARRAY['volière']::TEXT[], 'Psittacula krameri : espèce CITES annexe II.'),
  ('cat_' || substr(md5('calopsitte::Gris (sauvage)'), 1, 20), 'Gris (sauvage)', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Lutino'), 1, 20), 'Lutino', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Perlé'), 1, 20), 'Perlé', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Pie'), 1, 20), 'Pie', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Cinnamon'), 1, 20), 'Cinnamon', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Face blanche'), 1, 20), 'Face blanche', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Albinos'), 1, 20), 'Albinos', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('calopsitte::Fallow'), 1, 20), 'Fallow', 'calopsitte', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::Roseicollis'), 1, 20), 'Roseicollis', 'inseparable', 'Afrique australe', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::De Fischer'), 1, 20), 'De Fischer', 'inseparable', 'Afrique de l''Est', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::Masqué (personata)'), 1, 20), 'Masqué (personata)', 'inseparable', 'Afrique de l''Est', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::De Lilian (nyasa)'), 1, 20), 'De Lilian (nyasa)', 'inseparable', 'Afrique de l''Est', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::Nigrigenis'), 1, 20), 'Nigrigenis', 'inseparable', 'Afrique australe', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('inseparable::Taranta'), 1, 20), 'Taranta', 'inseparable', 'Éthiopie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Gris du Gabon'), 1, 20), 'Gris du Gabon', 'perroquet', 'Afrique centrale', ARRAY['compagnie']::TEXT[], 'CITES annexe I : cession encadrée, marquage et registre obligatoires.'),
  ('cat_' || substr(md5('perroquet::Youyou du Sénégal'), 1, 20), 'Youyou du Sénégal', 'perroquet', 'Afrique de l''Ouest', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Amazone à front bleu'), 1, 20), 'Amazone à front bleu', 'perroquet', 'Amérique du Sud', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Ara ararauna'), 1, 20), 'Ara ararauna', 'perroquet', 'Amérique du Sud', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Ara chloroptère'), 1, 20), 'Ara chloroptère', 'perroquet', 'Amérique du Sud', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Cacatoès rosalbin'), 1, 20), 'Cacatoès rosalbin', 'perroquet', 'Australie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Cacatoès à huppe jaune'), 1, 20), 'Cacatoès à huppe jaune', 'perroquet', 'Indonésie', ARRAY['volière']::TEXT[], 'CITES annexe I.'),
  ('cat_' || substr(md5('perroquet::Eclectus'), 1, 20), 'Eclectus', 'perroquet', 'Océanie', ARRAY['volière']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Pionus'), 1, 20), 'Pionus', 'perroquet', 'Amérique du Sud', ARRAY['compagnie']::TEXT[], NULL),
  ('cat_' || substr(md5('perroquet::Conure soleil'), 1, 20), 'Conure soleil', 'perroquet', 'Amérique du Sud', ARRAY['volière']::TEXT[], 'CITES annexe II.'),
  ('cat_' || substr(md5('canari::Malinois (waterslager)'), 1, 20), 'Malinois (waterslager)', 'canari', 'Belgique', ARRAY['chant']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Harz (harzer roller)'), 1, 20), 'Harz (harzer roller)', 'canari', 'Allemagne', ARRAY['chant']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Timbrado'), 1, 20), 'Timbrado', 'canari', 'Espagne', ARRAY['chant']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Frisé du Nord'), 1, 20), 'Frisé du Nord', 'canari', 'France', ARRAY['posture', 'exposition']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Frisé parisien'), 1, 20), 'Frisé parisien', 'canari', 'France', ARRAY['posture', 'exposition']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Bossu belge'), 1, 20), 'Bossu belge', 'canari', 'Belgique', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Gloster'), 1, 20), 'Gloster', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Yorkshire'), 1, 20), 'Yorkshire', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Norwich'), 1, 20), 'Norwich', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Border'), 1, 20), 'Border', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Lizard'), 1, 20), 'Lizard', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Fife fancy'), 1, 20), 'Fife fancy', 'canari', 'Royaume-Uni', ARRAY['posture']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Canari de couleur rouge'), 1, 20), 'Canari de couleur rouge', 'canari', 'Europe', ARRAY['couleur']::TEXT[], NULL),
  ('cat_' || substr(md5('canari::Canari mosaïque'), 1, 20), 'Canari mosaïque', 'canari', 'Europe', ARRAY['couleur']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Gris (sauvage)'), 1, 20), 'Gris (sauvage)', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Blanc'), 1, 20), 'Blanc', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Pie'), 1, 20), 'Pie', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Isabelle'), 1, 20), 'Isabelle', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Joues noires'), 1, 20), 'Joues noires', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Masqué'), 1, 20), 'Masqué', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Poitrine orange'), 1, 20), 'Poitrine orange', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('mandarin::Huppé'), 1, 20), 'Huppé', 'mandarin', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('tortue_terrestre::Tortue d''Hermann'), 1, 20), 'Tortue d''Hermann', 'tortue_terrestre', 'Méditerranée', ARRAY['terrarium', 'extérieur']::TEXT[], 'CITES annexe II : déclaration de détention (i-Fap) et marquage obligatoires.'),
  ('cat_' || substr(md5('tortue_terrestre::Tortue grecque'), 1, 20), 'Tortue grecque', 'tortue_terrestre', 'Méditerranée', ARRAY['extérieur']::TEXT[], 'CITES annexe II.'),
  ('cat_' || substr(md5('tortue_terrestre::Tortue bordée'), 1, 20), 'Tortue bordée', 'tortue_terrestre', 'Grèce', ARRAY['extérieur']::TEXT[], 'CITES annexe II.'),
  ('cat_' || substr(md5('tortue_terrestre::Tortue des steppes (Horsfield)'), 1, 20), 'Tortue des steppes (Horsfield)', 'tortue_terrestre', 'Asie centrale', ARRAY['extérieur']::TEXT[], 'CITES annexe II.'),
  ('cat_' || substr(md5('tortue_terrestre::Tortue sillonnée'), 1, 20), 'Tortue sillonnée', 'tortue_terrestre', 'Sahel', ARRAY['extérieur']::TEXT[], 'Adulte > 40 kg : engagement à vie, CITES annexe II.'),
  ('cat_' || substr(md5('tortue_terrestre::Tortue étoilée d''Inde'), 1, 20), 'Tortue étoilée d''Inde', 'tortue_terrestre', 'Inde', ARRAY['terrarium']::TEXT[], 'CITES annexe I.'),
  ('cat_' || substr(md5('gecko_leopard::Sauvage (wild type)'), 1, 20), 'Sauvage (wild type)', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::High yellow'), 1, 20), 'High yellow', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Tangerine'), 1, 20), 'Tangerine', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Mack snow'), 1, 20), 'Mack snow', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Albinos Tremper'), 1, 20), 'Albinos Tremper', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Albinos Bell'), 1, 20), 'Albinos Bell', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Albinos Rainwater'), 1, 20), 'Albinos Rainwater', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Blizzard'), 1, 20), 'Blizzard', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Murphy patternless'), 1, 20), 'Murphy patternless', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Eclipse'), 1, 20), 'Eclipse', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Radar'), 1, 20), 'Radar', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_leopard::Super giant'), 1, 20), 'Super giant', 'gecko_leopard', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Patternless'), 1, 20), 'Patternless', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Flame'), 1, 20), 'Flame', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Harlequin'), 1, 20), 'Harlequin', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Extreme harlequin'), 1, 20), 'Extreme harlequin', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Pinstripe'), 1, 20), 'Pinstripe', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Dalmatien'), 1, 20), 'Dalmatien', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Tricolore'), 1, 20), 'Tricolore', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('gecko_crete::Lilly white'), 1, 20), 'Lilly white', 'gecko_crete', NULL, ARRAY['variété']::TEXT[], 'Létal à l''état homozygote : ne jamais accoupler deux Lilly white.'),
  ('cat_' || substr(md5('pogona::Classique (sauvage)'), 1, 20), 'Classique (sauvage)', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Hypomélanistique'), 1, 20), 'Hypomélanistique', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Translucide'), 1, 20), 'Translucide', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Leatherback'), 1, 20), 'Leatherback', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Citrus'), 1, 20), 'Citrus', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Red'), 1, 20), 'Red', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Witblits'), 1, 20), 'Witblits', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Zero'), 1, 20), 'Zero', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Dunner'), 1, 20), 'Dunner', 'pogona', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('pogona::Silkback'), 1, 20), 'Silkback', 'pogona', NULL, ARRAY['variété']::TEXT[], 'Sans écailles : fragilité cutanée majeure, sélection déconseillée.'),
  ('cat_' || substr(md5('serpent_des_bles::Sauvage (carolina)'), 1, 20), 'Sauvage (carolina)', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Okeetee'), 1, 20), 'Okeetee', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Amélanistique'), 1, 20), 'Amélanistique', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Anérythrique'), 1, 20), 'Anérythrique', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Snow'), 1, 20), 'Snow', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Blizzard'), 1, 20), 'Blizzard', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Motley'), 1, 20), 'Motley', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Stripe'), 1, 20), 'Stripe', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Lavande'), 1, 20), 'Lavande', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Caramel'), 1, 20), 'Caramel', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('serpent_des_bles::Palmetto'), 1, 20), 'Palmetto', 'serpent_des_bles', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Classique (wild type)'), 1, 20), 'Classique (wild type)', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Pastel'), 1, 20), 'Pastel', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Super pastel'), 1, 20), 'Super pastel', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Mojave'), 1, 20), 'Mojave', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Lesser'), 1, 20), 'Lesser', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Butter'), 1, 20), 'Butter', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Banana'), 1, 20), 'Banana', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Albinos'), 1, 20), 'Albinos', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Piebald'), 1, 20), 'Piebald', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Clown'), 1, 20), 'Clown', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Ghost'), 1, 20), 'Ghost', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Enchi'), 1, 20), 'Enchi', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Yellow belly'), 1, 20), 'Yellow belly', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('python_royal::Fire'), 1, 20), 'Fire', 'python_royal', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Sauvage (wild type)'), 1, 20), 'Sauvage (wild type)', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Leucistique'), 1, 20), 'Leucistique', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Albinos doré'), 1, 20), 'Albinos doré', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Albinos blanc'), 1, 20), 'Albinos blanc', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Mélanoïde'), 1, 20), 'Mélanoïde', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL),
  ('cat_' || substr(md5('axolotl::Copper'), 1, 20), 'Copper', 'axolotl', NULL, ARRAY['variété']::TEXT[], NULL)
ON CONFLICT ("espece_animale_id", "nom") DO NOTHING;
